const jsonData = [
  {
    "Accounts": "Bank1",
    "Years (Date)": "2019",
    "Number of People Retweeted": 3915,
    "Number of People Liked": 3438,
    "Number of Positive People": 4334,
    "Number of Negative People": 2258,
    "Number of Neutral People": 1078,
    "Number of Positive Predictions": 1427,
    "Number of Negative Predictions": 1588,
    "Number of Neutral Predictions": 1134
  },
  {
    "Accounts": "Bank1",
    "Years (Date)": "2020",
    "Number of People Retweeted": 3915,
    "Number of People Liked": 3438,
    "Number of Positive People": 4334,
    "Number of Negative People": 2258,
    "Number of Neutral People": 1078,
    "Number of Positive Predictions": 1427,
    "Number of Negative Predictions": 1588,
    "Number of Neutral Predictions": 1134
  },
  {
    "Accounts": "Bank1",
    "Years (Date)": "2021",
    "Number of People Retweeted": 3915,
    "Number of People Liked": 3438,
    "Number of Positive People": 4334,
    "Number of Negative People": 2258,
    "Number of Neutral People": 1078,
    "Number of Positive Predictions": 1427,
    "Number of Negative Predictions": 1588,
    "Number of Neutral Predictions": 1134
  },
  {
    "Accounts": "Bank1",
    "Years (Date)": "2022",
    "Number of People Retweeted": 3915,
    "Number of People Liked": 3438,
    "Number of Positive People": 4334,
    "Number of Negative People": 2258,
    "Number of Neutral People": 1078,
    "Number of Positive Predictions": 1427,
    "Number of Negative Predictions": 1588,
    "Number of Neutral Predictions": 1134
  },
  {
    "Accounts": "Bank1",
    "Years (Date)": "2023",
    "Number of People Retweeted": 3915,
    "Number of People Liked": 3438,
    "Number of Positive People": 4334,
    "Number of Negative People": 2258,
    "Number of Neutral People": 1078,
    "Number of Positive Predictions": 1427,
    "Number of Negative Predictions": 1588,
    "Number of Neutral Predictions": 1134
  },
  {
    "Accounts": "bank2",
    "Years (Date)": "2019",
    "Number of People Retweeted": 1371,
    "Number of People Liked": 1483,
    "Number of Positive People": 4792,
    "Number of Negative People": 3694,
    "Number of Neutral People": 1631,
    "Number of Positive Predictions": 1250,
    "Number of Negative Predictions": 1327,
    "Number of Neutral Predictions": 1149
  },
  {
    "Accounts": "bank2",
    "Years (Date)": "2020",
    "Number of People Retweeted": 1371,
    "Number of People Liked": 1483,
    "Number of Positive People": 4792,
    "Number of Negative People": 3694,
    "Number of Neutral People": 1631,
    "Number of Positive Predictions": 1250,
    "Number of Negative Predictions": 1327,
    "Number of Neutral Predictions": 1149
  },  {
    "Accounts": "bank2",
    "Years (Date)": "2021",
    "Number of People Retweeted": 1371,
    "Number of People Liked": 1483,
    "Number of Positive People": 4792,
    "Number of Negative People": 3694,
    "Number of Neutral People": 1631,
    "Number of Positive Predictions": 1250,
    "Number of Negative Predictions": 1327,
    "Number of Neutral Predictions": 1149
  },  {
    "Accounts": "bank2",
    "Years (Date)": "2022",
    "Number of People Retweeted": 1371,
    "Number of People Liked": 1483,
    "Number of Positive People": 4792,
    "Number of Negative People": 3694,
    "Number of Neutral People": 1631,
    "Number of Positive Predictions": 1250,
    "Number of Negative Predictions": 1327,
    "Number of Neutral Predictions": 1149
  },
  {
    "Accounts": "bank2",
    "Years (Date)": "2023",
    "Number of People Retweeted": 1371,
    "Number of People Liked": 1483,
    "Number of Positive People": 4792,
    "Number of Negative People": 3694,
    "Number of Neutral People": 1631,
    "Number of Positive Predictions": 1250,
    "Number of Negative Predictions": 1327,
    "Number of Neutral Predictions": 1149
  },
  {
    "Accounts": "Bank3",
    "Years (Date)": "2019",
    "Number of People Retweeted": 1728,
    "Number of People Liked": 3124,
    "Number of Positive People": 4498,
    "Number of Negative People": 1740,
    "Number of Neutral People": 1770,
    "Number of Positive Predictions": 1434,
    "Number of Negative Predictions": 1222,
    "Number of Neutral Predictions": 1010
  },
  {
    "Accounts": "Bank3",
    "Years (Date)": "2020",
    "Number of People Retweeted": 1728,
    "Number of People Liked": 3124,
    "Number of Positive People": 4498,
    "Number of Negative People": 1740,
    "Number of Neutral People": 1770,
    "Number of Positive Predictions": 1434,
    "Number of Negative Predictions": 1222,
    "Number of Neutral Predictions": 1010
  },
  {
    "Accounts": "Bank3",
    "Years (Date)": "2021",
    "Number of People Retweeted": 1728,
    "Number of People Liked": 3124,
    "Number of Positive People": 4498,
    "Number of Negative People": 1740,
    "Number of Neutral People": 1770,
    "Number of Positive Predictions": 1434,
    "Number of Negative Predictions": 1222,
    "Number of Neutral Predictions": 1010
  },
  {
    "Accounts": "Bank3",
    "Years (Date)": "2022",
    "Number of People Retweeted": 1728,
    "Number of People Liked": 3124,
    "Number of Positive People": 4498,
    "Number of Negative People": 1740,
    "Number of Neutral People": 1770,
    "Number of Positive Predictions": 1434,
    "Number of Negative Predictions": 1222,
    "Number of Neutral Predictions": 1010
  },
  {
    "Accounts": "Bank3",
    "Years (Date)": "2023",
    "Number of People Retweeted": 1728,
    "Number of People Liked": 3124,
    "Number of Positive People": 4498,
    "Number of Negative People": 1740,
    "Number of Neutral People": 1770,
    "Number of Positive Predictions": 1434,
    "Number of Negative Predictions": 1222,
    "Number of Neutral Predictions": 1010
  },
  {
    "Accounts": "Fintech4",
    "Years (Date)": "2019",
    "Number of People Retweeted": 1105,
    "Number of People Liked": 1559,
    "Number of Positive People": 1223,
    "Number of Negative People": 3804,
    "Number of Neutral People": 1056,
    "Number of Positive Predictions": 1603,
    "Number of Negative Predictions": 1770,
    "Number of Neutral Predictions": 1570
  },
  {
    "Accounts": "Fintech4",
    "Years (Date)": "2020",
    "Number of People Retweeted": 1105,
    "Number of People Liked": 1559,
    "Number of Positive People": 1223,
    "Number of Negative People": 3804,
    "Number of Neutral People": 1056,
    "Number of Positive Predictions": 1603,
    "Number of Negative Predictions": 1770,
    "Number of Neutral Predictions": 1570
  },
  {
    "Accounts": "Fintech4",
    "Years (Date)": "2021",
    "Number of People Retweeted": 1105,
    "Number of People Liked": 1559,
    "Number of Positive People": 1223,
    "Number of Negative People": 3804,
    "Number of Neutral People": 1056,
    "Number of Positive Predictions": 1603,
    "Number of Negative Predictions": 1770,
    "Number of Neutral Predictions": 1570
  },
  {
    "Accounts": "Fintech4",
    "Years (Date)": "2022",
    "Number of People Retweeted": 1105,
    "Number of People Liked": 1559,
    "Number of Positive People": 1223,
    "Number of Negative People": 3804,
    "Number of Neutral People": 1056,
    "Number of Positive Predictions": 1603,
    "Number of Negative Predictions": 1770,
    "Number of Neutral Predictions": 1570
  },
  {
    "Accounts": "Fintech4",
    "Years (Date)": "2023",
    "Number of People Retweeted": 1105,
    "Number of People Liked": 1559,
    "Number of Positive People": 1223,
    "Number of Negative People": 3804,
    "Number of Neutral People": 1056,
    "Number of Positive Predictions": 1603,
    "Number of Negative Predictions": 1770,
    "Number of Neutral Predictions": 1570
  },
  {
    "Accounts": "Fintech5",
    "Years (Date)": "2019",
    "Number of People Retweeted": 2338,
    "Number of People Liked": 3565,
    "Number of Positive People": 2015,
    "Number of Negative People": 1410,
    "Number of Neutral People": 1207,
    "Number of Positive Predictions": 1275,
    "Number of Negative Predictions": 1675,
    "Number of Neutral Predictions": 1754
  },
  {
    "Accounts": "Fintech5",
    "Years (Date)": "2020",
    "Number of People Retweeted": 2338,
    "Number of People Liked": 3565,
    "Number of Positive People": 2015,
    "Number of Negative People": 1410,
    "Number of Neutral People": 1207,
    "Number of Positive Predictions": 1275,
    "Number of Negative Predictions": 1675,
    "Number of Neutral Predictions": 1754
  },
  {
    "Accounts": "Fintech5",
    "Years (Date)": "2021",
    "Number of People Retweeted": 2338,
    "Number of People Liked": 3565,
    "Number of Positive People": 2015,
    "Number of Negative People": 1410,
    "Number of Neutral People": 1207,
    "Number of Positive Predictions": 1275,
    "Number of Negative Predictions": 1675,
    "Number of Neutral Predictions": 1754
  },
  {
    "Accounts": "Fintech5",
    "Years (Date)": "2022",
    "Number of People Retweeted": 2338,
    "Number of People Liked": 3565,
    "Number of Positive People": 2015,
    "Number of Negative People": 1410,
    "Number of Neutral People": 1207,
    "Number of Positive Predictions": 1275,
    "Number of Negative Predictions": 1675,
    "Number of Neutral Predictions": 1754
  },
  {
    "Accounts": "Fintech5",
    "Years (Date)": "2023",
    "Number of People Retweeted": 2338,
    "Number of People Liked": 3565,
    "Number of Positive People": 2015,
    "Number of Negative People": 1410,
    "Number of Neutral People": 1207,
    "Number of Positive Predictions": 1275,
    "Number of Negative Predictions": 1675,
    "Number of Neutral Predictions": 1754
  }
];

module.exports = jsonData;